# Defines if the HTTP endpoint is enabled.
#http.enabled: false

# The HTTP endpoint will bind to this hostname, IP address, unix socket or named pipe.
# When using IP addresses, it is recommended to only use localhost.
#http.host: localhost

# Port on which the HTTP endpoint will bind. Default is 5066.
#http.port: 5066

# Define which user should be owning the named pipe.
#http.named_pipe.user:

# Define which the permissions that should be applied to the named pipe, use the Security
# Descriptor Definition Language (SDDL) to define the permission. This option cannot be used with
# `http.user`.
#http.named_pipe.security_descriptor:

#============================= Process Security ================================

# Enable or disable seccomp system call filtering on Linux. Default is enabled.
#seccomp.enabled: true

#================================= Migration ==================================

# This allows to enable 6.7 migration aliases
#migration.6_to_7.enabled: falseroot@a26c6c716885:/etc/ansible#
root@a26c6c716885:/etc/ansible# clear
root@a26c6c716885:/etc/ansible# clear
root@a26c6c716885:/etc/ansible# ls
ansible.cfg  filebeat-config.yml  hosts  install-elk.yml  pentest.yml  roles
root@a26c6c716885:/etc/ansible# hosts
bash: hosts: command not found
root@a26c6c716885:/etc/ansible# nano hosts
root@a26c6c716885:/etc/ansible# ls
ansible.cfg  filebeat-config.yml  hosts  install-elk.yml  pentest.yml  roles
root@a26c6c716885:/etc/ansible# cat pentest.yml
---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
  - name: Uninstall Apache2 / DVWA runs on same port
    apt:
     name: apache 2
     state: absent

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes